## Python

In [19]:
#1. Write a Python program using lambda to calculate the square of a number entered by the user.

sq_num= lambda a:a**2
a=int(input("Enter you number: "))
print("Your entry: ",a)
print("square of your entry is: ", sq_num(a))

Enter you number:  3


Your entry:  3
square of your entry is:  9


In [37]:
#2. Use map to double all the elements in the list: [1, 2, 3, 4, 5].

lst=[1,2,3,4,5]
double_no=list(map(lambda a:a*2, lst))
print(f"double of {lst} is {double_no}")

double of [1, 2, 3, 4, 5] is [2, 4, 6, 8, 10]


In [43]:
#3. Use filter to extract all even numbers from the list: [10, 15, 20, 25, 30].

lst=[10, 15, 20, 25, 30]
even=list(filter(lambda a:a%2==0, lst))
print(f"even numbers from {lst} is {even}")

even numbers from [10, 15, 20, 25, 30] is [10, 20, 30]


In [61]:
#4. Write a one-liner lambda function to check if a given number is a palindrome.

a=int(input('enter a number: '))
palindrome= lambda a:str(a)==str(a)[::-1]
print(palindrome(a))

enter a number:  3443


True


In [73]:
#5. Write a function that takes a variable number of arguments (*args) and returns their sum

sum
def add_numbers(*args):
     return(sum(args))

In [75]:
add_numbers(2,3)

5

In [79]:
add_numbers(3,5,8)

16

In [98]:
#6. Write a function that uses **kwargs to accept a student’s details (name, age, and grade) and print them in a formatted string.

def student_info(**kwargs):
    for key, value in kwargs.items():
        print(key, value)

In [100]:
student_info(name=['pooja','raj'],age=[23,21],grade=['A','B'])

name ['pooja', 'raj']
age [23, 21]
grade ['A', 'B']


In [159]:
#7. Create a class Person with attributes name and age. Add a method greet that prints a greeting with the name.
#Create an object of the class and call the greet method.

class info:
    def __init__(self):
        self.name = input('enter your name: ')
        self.age = input('enter your age: ')

    def greeting(self):
        return (f'Hello! How are you {self.name}')

In [161]:
#create object
a=info()

enter your name:  Ishika
enter your age:  22


In [163]:
print(a.greeting())

Hello! How are you Ishika


In [201]:
#8. Create a base class Animal with a method speak that prints "I am an animal."
#Create a derived class Dog that overrides the speak method to print "I am a dog."

class animal():
    def speak(self):
        print('i am animal')

class dog(animal):
    def speak(self):
        print('i am a dog')

In [205]:
#create object
animal=animal()
animal.speak()

i am animal


In [203]:
dog=dog()
dog.speak()

i am a dog


In [219]:
#9. Define a class Car with attributes brand and year. Add a method to display the car details.
#Use the __init__ method to initialize the attributes.

class car():

    def __init__(self, brand=input("enter brand: "),
                year=int(input("enter year: "))):

        self.brand=brand
        self.year=year

    def display(self):
        return(f'car details: {self.brand}, {self.year}')

enter brand:  tesla
enter year:  2022


In [221]:
car=car()
car.display()

'car details: tesla, 2022'

In [223]:
#10.Write a program to print the first 10 natural numbers using a for loop.

for i in range(1,11):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [225]:
#11.Write a program to calculate the sum of all numbers in a list: [5, 10, 15, 20] using a for loop.

sum=0
lst=[5, 10, 15, 20]
for i in lst:
    sum+=i
    i+=1

print(sum)

50


In [20]:
#12.Write a Python program to print the multiplication table of a given number using a while loop.

num=int(input('Enter a number: '))
count=int(input('Enter a count: '))

i=1
while i<=count:
    prod=num*i
    print(f'{num} X {i} = {prod}')
    i+=1

Enter a number:  3
Enter a count:  4


3 X 1 = 3
3 X 2 = 6
3 X 3 = 9
3 X 4 = 12


In [5]:
#13.Write a program to find the factorial of a number using a while loop.

i=1
fact=1
num=int(input('Enter a number: '))

while i<=num:
    fact=fact*i
    i+=1

print(fact)

Enter a number:  5


120


In [7]:
#14.Write a Python program to check if a number entered by the user is even or odd.

num=int(input("enter a number: "))
print("number entered: ", num)

if num%2==0:
    print(f'{num} is even')

if num%2==1:
    print(f'{num} is odd')

enter a number:  3


number entered:  3
3 is odd


In [9]:
#15.Write a Python program to determine the grade of a student based on theirmarks:
#• Marks >= 90: Grade A
#• Marks >= 75: Grade B
#• Marks >= 50: Grade C
#• Otherwise: Grade F

marks=int(input("enter your marksr: "))

if marks >= 90:
    print('You got A grade')
elif marks >= 75:
    print('You got B grade')
elif marks >= 50:
    print('You got C grade')
else:
    print('You got F grade')

enter your marksr:  55


You got C grade


In [17]:
#16.Write a Python function to check if a string is a palindrome.

string=input("enter a string: ")
print("string entered: ", string)
palindrome= lambda a:str(a)==str(a)[::-1]

print(palindrome(string))

enter a string:  abba


string entered:  abba
True


In [1]:
#17.Write a function to find the maximum of three numbers entered by the user.

def max_value(a,b,c):
    if a>b and a>c:
        print('a is largest')
    elif b>a and b>c:
        print('b is largest')
    else:
        print('c is largest')

max_value(213,5,44)

a is largest


In [17]:
#18.Write a function that takes a list of numbers and returns the largest number

def largest(numbers):
    #Returns the largest number in a list
    return max(numbers)

# Example usage
numbers = [10, 45, 23, 78, 12]
largest_number = largest(numbers)
print(f"The largest number is: {largest_number}")

The largest number is: 78


In [21]:
#19.Write a Python program to reverse a string using a for loop.

string=input('enter a string: ')
rev_str=string[::-1]
print(rev_str)

enter a string:  ishika


akihsi


In [31]:
#20.Write a Python program to count the number of vowels in a string entered by the user.

string=input('enter a string: ')
print(string)

count = 0

# Loop through each character in the list
for char in string:
    # Check if the character is a vowel (lowercase or uppercase)
    if char in 'aeiouAEIOU':
        count += 1  # Increment the count if it's a vowel

# Print the total count of vowels
print(f"Number of vowels: {count}")

enter a string:  ishika


ishika
Number of vowels: 3


## Numpy

In [37]:
import numpy as np

In [45]:
#1. Create a NumPy array of zeros with shape (3, 4).

arr=np.zeros([3,4])
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [47]:
#2. Create a NumPy array of ones with shape (2, 5).

arr=np.ones([2,5])
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [51]:
#3. Create a NumPy matrix with the values from 1 to 10 using np.arange().

arr=np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [57]:
#4. Create a NumPy array with numbers from 0 to 1 (inclusive) with a step size of 0.1 using np.arange().

arr=np.arange(0,1.1,0.1)
print(arr)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [63]:
#5. Create a NumPy array with 10 equally spaced values between 0 and 1 using np.linspace() with endpoint=False.

#linspace(start,end, number of elements)
arr=np.linspace(0,1,10)
print(arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [71]:
#6. Write a NumPy program to compute the square root of each element in the array [1, 4, 9, 16].

arr=[1, 4, 9, 16]
arr_sq=np.sqrt(arr)
arr_sq

array([1., 2., 3., 4.])

In [83]:
#7. Compute the sum of all elements in the array np.array([2, 3, 4, 5, 6]).

arr=np.array([2, 3, 4, 5, 6])
sum_arr=np.sum(arr)
print(sum_arr)

20


In [87]:
#8. Find the minimum value in the array np.array([1, 5, 9, 3, 6]) using np.min().

arr=np.array([1, 5, 9, 3, 6])
minimum=np.min(arr)
print(minimum)

1


In [89]:
#9. Find the maximum value in the array np.array([1, 5, 9, 3, 6]) using np.max().

arr=np.array([1, 5, 9, 3, 6])
maxi=np.max(arr)
print(maxi)

9


In [91]:
#10.Use np.ceil() to round the elements of the array np.array([1.2, 2.5, 3.7, 4.9]) to the nearest greater integer.

arr=np.array([1.2, 2.5, 3.7, 4.9])
arr_new=np.ceil(arr)
print(arr_new)

[2. 3. 4. 5.]


In [97]:
#11.Generate an array of 5 random integers between 10 and 50 using np.random.randint().

rand_int=np.random.randint(10,50,5)
rand_arr=np.array(rand_int)
rand_arr

array([25, 34, 43, 39, 12], dtype=int32)

In [115]:
#12.Generate an array of 5 random floating-point numbers between 0 and 1 using np.random.rand().

rand_arr=np.random.rand(5)
print(rand_arr)

[0.23388407 0.10966515 0.6988854  0.02952841 0.98955404]


In [113]:
#13.Generate a 3x3 matrix of random numbers from a normal distribution with mean 0 
#and standard deviation 1 using np.random.randn().

#np.random.randn(rows,columns)
arr=np.random.randn(3,3)
arr

array([[-0.78621004,  0.01690136,  0.77001   ],
       [ 0.57285002, -0.09954469, -1.06937882],
       [-0.40692519,  0.11364287, -0.5253512 ]])

In [127]:
#14.Use np.where() to replace all elements greater than 5 in the array [1, 2, 3, 6, 7, 8] with 10.

arr=np.array([1, 2, 3, 6, 7, 8])
ar=np.where(arr > 5,10,arr)
ar

array([ 1,  2,  3, 10, 10, 10])

In [133]:
#15.Use np.where() to find the index of the first element that is greater than 3 in the array [1, 2, 3, 4, 5].

arr=np.array([1,2,3,4,5])
index=np.where(arr>3)[0][0]
print('index of first number greater than 3: ',index)

index of first number greater than 3:  3


In [137]:
#16.Perform matrix addition of two matrices A = np.array([[1, 2], [3, 4]]) and B = np.array([[5, 6], [7, 8]]).

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

add=A+B
add

array([[ 6,  8],
       [10, 12]])

In [139]:
#17.Perform element-wise matrix division of matrix A = np.array([[1, 2], [3, 4]]) by
#matrix B = np.array([[5, 6], [7, 8]]).

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

division=A/B
division

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [141]:
#18.Perform matrix multiplication of matrices A = np.array([[1, 2], [3, 4]]) and B =
#np.array([[5, 6], [7, 8]]).

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

prod=A*B
prod

array([[ 5, 12],
       [21, 32]])

In [145]:
#19.Reshape a 1D array [1, 2, 3, 4, 5, 6] into a 2x3 matrix using np.reshape()

ar=np.reshape(np.array([1, 2, 3, 4, 5, 6]),(2,3))
ar

array([[1, 2, 3],
       [4, 5, 6]])

In [147]:
#20.Slice the first two elements from the array np.array([10, 20, 30, 40, 50]).

arr=np.array([10, 20, 30, 40, 50])
new_arr=arr[0:2]
new_arr

array([10, 20])