<a href="https://colab.research.google.com/github/skyish21/AIML-Python/blob/main/DL/PyTorch_1_Intro_to_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Tensors

- A torch.tensor is a multi-dimensional matrix containing elements of a single data type.
- Similar to numpy arrays, but full of fun things that make them work better on GPU's (vs regualer CPU's).
- Default data type is float 32.
- More suitable for deep learning than a numpy array.

In [4]:
import torch
import numpy as np

## Lists

In [5]:
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [6]:
multi_dimensional_array = [[12,23,1,23,4],[3,2,12,43]]
multi_dimensional_array

[[12, 23, 1, 23, 4], [3, 2, 12, 43]]

## Numpy Arrays

In [7]:
np1 = np.random.rand(3,4) # 3 rows, 4 columns with random values
np1

array([[0.68355461, 0.24091566, 0.09282846, 0.1829584 ],
       [0.29557241, 0.83858992, 0.32477177, 0.46360738],
       [0.71040729, 0.73948076, 0.76949878, 0.02656566]])

In [8]:
np1.dtype

dtype('float64')

## Tensors

In [9]:
tensor_2d = torch.randn(3,4) # 3 rows, 4 columns with random values
tensor_2d

tensor([[ 1.1709, -0.1043,  0.0106, -1.2777],
        [ 1.2898, -1.2038,  0.6172,  0.1314],
        [ 1.4141, -0.5870, -0.8589,  1.1614]])

In [10]:
tensor_3d = torch.zeros(2,3,4) # 2 3x4 tensors with only zeros
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
tensor_3d.dtype

torch.float32

In [11]:
## create tensor from numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.6836, 0.2409, 0.0928, 0.1830],
        [0.2956, 0.8386, 0.3248, 0.4636],
        [0.7104, 0.7395, 0.7695, 0.0266]], dtype=torch.float64)