<a href="https://colab.research.google.com/github/skyish21/AIML-Python/blob/main/DL/Pytorch_3%20Tensor%20Maths.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Tensor Math operations
- Add, Subtract, Multiply, Divide, Remainders, Exponents
- Shorthand and Longhand
- Reassignment

In [25]:
import torch
import numpy as np

In [26]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [27]:
# addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [28]:
# addition longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [29]:
# subtract
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [30]:
# subtract longhand
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [31]:
# multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [32]:
# multiplication longhand
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [33]:
torch.multiply(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

In [34]:
# divide
tensor_b / tensor_a # converts it float

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [35]:
# divide by any number
tensor_b / 2

tensor([2.5000, 3.0000, 3.5000, 4.0000])

In [36]:
# division longhand
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [37]:
# remainders using modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [38]:
# remainder longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [39]:
# exponents / power
tensor_a ** tensor_b

tensor([    1,    64,  2187, 65536])

In [40]:
# exponent / power longhand
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [41]:
# another way to do longhand
tensor_a.add(tensor_b)
tensor_a

tensor([1, 2, 3, 4])

In [42]:
# reassignment
tensor_a = tensor_a + tensor_b
tensor_a

tensor([ 6,  8, 10, 12])

In [44]:
# reassignment longhand
tensor_a = torch.tensor([1,2,3,4])
tensor_a.add_(tensor_b)
tensor_a

tensor([ 6,  8, 10, 12])