In [1]:
#numpy = numpy means Numerical Python. It is used to do numerical calculations.
# we have to import numpy as sqlite3.

In [3]:
import numpy as np

In [5]:
#check all the function of  numpy.
print(dir(np))

['False_', 'ScalarType', 'True_', '_CopyMode', '_NoValue', '__NUMPY_SETUP__', '__all__', '__array_api_version__', '__array_namespace_info__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__expired_attributes__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__numpy_submodules__', '__package__', '__path__', '__spec__', '__version__', '_array_api_info', '_core', '_distributor_init', '_expired_attrs_2_0', '_get_promotion_state', '_globals', '_int_extended_msg', '_mat', '_msg', '_no_nep50_warning', '_pyinstaller_hooks_dir', '_pytesttester', '_set_promotion_state', '_specific_msg', '_type_info', '_typing', '_utils', 'abs', 'absolute', 'acos', 'acosh', 'add', 'all', 'allclose', 'amax', 'amin', 'angle', 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arctan', 'arctan2', 'arctanh', 'argmax', 'argmin', 'argpartition', 'argsort', 'argwhere', 'around', 'array', 'arr

In [7]:
print(np.sqrt(36)) #get sqyare root

6.0


In [9]:
print('minimum: ', np.amin([33,445,6,73])) #print min value

minimum:  6


In [11]:
print('minimum: ', np.min([33,445,6,73])) #another method to print min

minimum:  6


In [13]:
print('maximun: ', np.amax([33,445,6,73])) #print max value

maximun:  445


In [15]:
print('maximun: ', np.max([33,445,6,73])) #another way to print max

maximun:  445


In [17]:
print(np.ceil(31.4)) #rounds ups the input value

32.0


In [19]:
print((np.sqrt(11)))
print(np.ceil(np.sqrt(11)))

3.3166247903554
4.0


In [21]:
print(np.sqrt([5,10,15])) 
print(np.sum(np.sqrt([5,10,15])))

#first square root, then add the values and then round up using ceil funtion
print(np.ceil(np.sum(np.sqrt([5,10,15]))))

[2.23606798 3.16227766 3.87298335]
9.271328983875588
10.0


In [23]:
np.array([31,4,5])

array([31,  4,  5])

In [27]:
type([51,9,23])

list

In [29]:
new_arr=np.array([4,3,1])

In [31]:
type(new_arr)

numpy.ndarray

In [41]:
#create 2D array
arr=np.array([[2,3,4],[5,6,7]])
arr

array([[2, 3, 4],
       [5, 6, 7]])

In [43]:
type(arr)

numpy.ndarray

In [45]:
arr.dtype #checking data type

dtype('int64')

In [47]:
np.array([11,24,53],dtype=float)

array([11., 24., 53.])

In [49]:
a=[1,2] #a=list
c=np.array(a)
print(c)

[1 2]


In [51]:
print(type(a))
print(type(c))

<class 'list'>
<class 'numpy.ndarray'>


In [55]:
#copy array into other
copy=np.asarray(c)
print(copy)

[1 2]


In [57]:
# Data Types

In [61]:
twoD_ar=[[1,2,3],[23,4,6],[67,32,7]]
arr=np.array(twoD_ar) #convert list to array

print("Type/class of this object : ", type(arr))
print("Here is the array \n------\n" ,arr,"\n-----------")
print("print dimension of this matrix : ", arr.ndim)  #ndim gives dimension, 2 for a matrix and 1 for vector
print("size of the matrix : ", arr.size)   #size shows total number elements
print("Shape of the matrix : ", arr.shape)   #shape shows how many rows and column
print("Data Type of the matrix ; ", arr.dtype)   #shoes which type

Type/class of this object :  <class 'numpy.ndarray'>
Here is the array 
------
 [[ 1  2  3]
 [23  4  6]
 [67 32  7]] 
-----------
print dimension of this matrix :  2
size of the matrix :  9
Shape of the matrix :  (3, 3)
Data Type of the matrix ;  int64


In [63]:
#arange and linspace

In [67]:
#arange

arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
#give a start point, stop point and step

arr=np.arange(3,21,2)
arr

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [73]:
#reverse

rev_arr=np.arange(23,0,-3)
rev_arr

array([23, 20, 17, 14, 11,  8,  5,  2])

In [79]:
#linspace -  linearly space numbers
#it gives 4 numbers between start and end point
#they have equal spacing/distance between them
np.linspace(45,84,4)

array([45., 58., 71., 84.])

In [81]:
#Include end points and check space between the points
#By default endpoint=True
#Bydefaul retstep=False

In [93]:
#start point=5
#end point = 7
#if endpoint true, it includes endpoint=7
np.linspace(5.0,7.0,num=4,endpoint=True,retstep=True)

(array([5.        , 5.66666667, 6.33333333, 7.        ]),
 np.float64(0.6666666666666666))

In [89]:
#when end point false, it doesnt include endpoint=7
np.linspace(5.0,7.0,num=4,endpoint=False,retstep=True)

(array([5. , 5.5, 6. , 6.5]), np.float64(0.5))

In [95]:
print(np.linspace(4.5678,25.9865,39,retstep=True))

(array([ 4.5678 ,  5.13145,  5.6951 ,  6.25875,  6.8224 ,  7.38605,
        7.9497 ,  8.51335,  9.077  ,  9.64065, 10.2043 , 10.76795,
       11.3316 , 11.89525, 12.4589 , 13.02255, 13.5862 , 14.14985,
       14.7135 , 15.27715, 15.8408 , 16.40445, 16.9681 , 17.53175,
       18.0954 , 18.65905, 19.2227 , 19.78635, 20.35   , 20.91365,
       21.4773 , 22.04095, 22.6046 , 23.16825, 23.7319 , 24.29555,
       24.8592 , 25.42285, 25.9865 ]), np.float64(0.56365))


In [97]:
#matrics creation

In [99]:
#matrics of zeros
print('vectors of zeros')
print(np.zeros([5]))

vectors of zeros
[0. 0. 0. 0. 0.]


In [101]:
print('vectors of zeros')
print(np.zeros([5,4]))

vectors of zeros
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [103]:
#matrics of ones
print('vectors of zeros')
print(np.ones([5]))

vectors of zeros
[1. 1. 1. 1. 1.]


In [107]:
print('vectors of zeros')
print(np.zeros([6,4]))

vectors of zeros
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [109]:
#cant create matrics for 2 or 3
#to print matrics of number other than 0/1, use below method:

In [113]:
#multiplication
print('vectors of zeros')
print(2*np.ones([5]))

vectors of zeros
[2. 2. 2. 2. 2.]


In [115]:
print('vectors of zeros')
print(3*np.ones([5,6]))

vectors of zeros
[[3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3.]]


In [119]:
#create diagonal matrix
#print elements in range of 30 with 5X6 shape
arr=np.arange(30).reshape(5,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
#Random number generation

In [129]:
print(np.random.seed(6)) #seed will generate a random number
print("Random number genration (from uniform distribution)")

#rand method uses uniform distrubiton method
#3,4 defines the shape
print(np.random.rand(3,4))

None
Random number genration (from uniform distribution)
[[0.89286015 0.33197981 0.82122912 0.04169663]
 [0.10765668 0.59505206 0.52981736 0.41880743]
 [0.33540785 0.62251943 0.43814143 0.73588211]]


In [127]:
print("Number from normal distribution with zero mean and standard deviation 1 i.e standard noraml")

#randn = it belongs to normal distribution
print(np.random.randn(3,4))

Number from normal distribution with zero mean and standard deviation 1 i.e standard noraml
[[ 2.63128056  0.60182225 -0.33588161  1.23773784]
 [ 0.11112817  0.12915125  0.07612761 -0.15512816]
 [ 0.63422534  0.810655    0.35480861  1.81259031]]


In [131]:
#print random intergers in range 5-20
print("Random integer vector : ",np.random.randint(5,20,10))

Random integer vector :  [17  9 16  7 10 18 15 14 11  7]


In [133]:
print("\n Random integer matrix")
#6,7 defines shape in range 1-30000
print(np.random.randint(1,30000,(6,7)))


 Random integer matrix
[[ 5036  5318 26086  5554  2693 28134  7231]
 [ 9809  3267  6272  9539 26944 10388 24150]
 [22141  7453 10298 24454  7475 19995 10063]
 [ 7288 25542 24903 24811 27712 19211 28484]
 [ 1366 29580 20610  5203 22436  9111 13436]
 [12138 10777 11185 28715 26564 21384 22053]]


In [ ]:
#One of the real time example of randint is

In [7]:
import numpy as np

In [13]:
def generate_otp():
    otp=np.random.randint(1000,10000,1)
    print("Your Otp is ",otp)
   
    while True:
     user_otp=int(input("Enter Your OTP Here"))
     print(user_otp)
        
     if otp==user_otp:
         print("Log in Sucessfully")
         break
     else:
         print("Your OTP is invalid")
         continue

In [15]:
generate_otp()

Your Otp is  [8350]


Enter Your OTP Here 4733


4733
Your OTP is invalid


Enter Your OTP Here 3453


3453
Your OTP is invalid


Enter Your OTP Here 8350


8350
Log in Sucessfully
