In [11]:
import numpy as np

In [13]:
#generate 10 numbers btw 0-9
age_number=np.random.randint(0,9,10)
age_number

array([8, 5, 4, 7, 4, 7, 7, 5, 8, 8], dtype=int32)

In [15]:
#set minimum and maximum age using a_min and a_max

In [17]:
# if we use clip method then all maximum and minimum value we can set as per our use
np.clip(age_number,a_min=2,a_max=6)

array([6, 5, 4, 6, 4, 6, 6, 5, 6, 6], dtype=int32)

In [19]:
#If you want to find actual age which is less then or greater than some salary use np.where
#np.where gives index detail

In [21]:
print(np.where(age_number>6))
#it gives index number where age is greater than 6

(array([0, 3, 5, 6, 8, 9]),)


In [23]:
#if u want actual data, use index
age_number[[3,5]]

array([7, 7], dtype=int32)

In [25]:
#similarly you can  check for any condition (<,>,=,==,<=,>=)


In [27]:
#Reshaping Otherways

In [102]:
import numpy as np
from numpy.random import randint as ri

In [31]:
#32 elements btw 5-25
a=ri(1,99,30)
print(a)

[23 12 56 91 81 32 41 53  2 75 19 28 94 86 40 60 76 24 65 10 19 31 70 95
 88 43 70 68 84 21]


In [33]:
#2 matices with 3 rows and 5 colums
b=a.reshape(2,3,5)
print(b)

[[[23 12 56 91 81]
  [32 41 53  2 75]
  [19 28 94 86 40]]

 [[60 76 24 65 10]
  [19 31 70 95 88]
  [43 70 68 84 21]]]


In [35]:
c=b.reshape(6,5)
print(c)

[[23 12 56 91 81]
 [32 41 53  2 75]
 [19 28 94 86 40]
 [60 76 24 65 10]
 [19 31 70 95 88]
 [43 70 68 84 21]]


In [37]:
print("Minimum of a is ",c.min())
print("Maximum of a is ",c.max())

Minimum of a is  2
Maximum of a is  95


In [39]:
#Sorting 

In [41]:
m=ri(1,100,25).reshape(5,5) #matrix of random integer
print("\n 5 X 5 matrix of random integer \n",'-'*50,'\n',m)
print("\n Here is the sorted matrix along each row \n",'-'*50,'\n',np.sort(m))#default axis=1
print("\n Here is the sorted matrix along each column \n",'-'*50,'\n',np.sort(m,axis=0))

#axis=0 sort by columns
#axis=1 sort by rows


 5 X 5 matrix of random integer 
 -------------------------------------------------- 
 [[41 88 66 92 10]
 [82  7 72 90 35]
 [51 54 14 67 44]
 [73 53 86 26 15]
 [69 20 82 96 53]]

 Here is the sorted matrix along each row 
 -------------------------------------------------- 
 [[10 41 66 88 92]
 [ 7 35 72 82 90]
 [14 44 51 54 67]
 [15 26 53 73 86]
 [20 53 69 82 96]]

 Here is the sorted matrix along each column 
 -------------------------------------------------- 
 [[41  7 14 26 10]
 [51 20 66 67 15]
 [69 53 72 90 35]
 [73 54 82 92 44]
 [82 88 86 96 53]]


In [43]:
#index and slicing

In [45]:
arr=np.arange(13,30)
print("array", arr)

array [13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [47]:
print("6th element of array: ", arr[5])

6th element of array:  18


In [49]:
print("element of array: ", arr[3:5])

element of array:  [16 17]


In [51]:
print("element of array: ", arr[3:])

element of array:  [16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [53]:
#store arr in abc and check 4th index of abc
abc=arr[4:]
abc

array([17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [55]:
#jump 2 from end of array
print("element of array: ", abc[-1::-2])

element of array:  [29 27 25 23 21 19 17]


In [57]:
#start, end, step size
print("element of array: ", abc[-1:-8:-1])

element of array:  [29 28 27 26 25 24 23]


In [59]:
print("Elements at 2nd 4th and 9th index are : ",arr[[2,4,9]])#Pass a list as a index to subset

Elements at 2nd 4th and 9th index are :  [15 17 22]


In [61]:
#list to array
matrix=[[1,2,3],[43,2,5],[6,5,2]]
new_matrix=np.array(matrix)
new_matrix

array([[ 1,  2,  3],
       [43,  2,  5],
       [ 6,  5,  2]])

In [63]:
print('entire row at index 2: ' , new_matrix[2])

entire row at index 2:  [6 5 2]


In [65]:
#matrix[row,column]
print('entire row at index 3: ' , new_matrix[:,:])

entire row at index 3:  [[ 1  2  3]
 [43  2  5]
 [ 6  5  2]]


In [67]:
print("Entire column at index  3:\n",new_matrix[:,1:])

Entire column at index  3:
 [[2 3]
 [2 5]
 [5 2]]


In [69]:
print("\nSubsetting Sub-Matricss\n---------")
print("Matrics with row indices 1 and 2 and column indices 3 and 4\n",new_matrix[1:2,1:2])


Subsetting Sub-Matricss
---------
Matrics with row indices 1 and 2 and column indices 3 and 4
 [[2]]


In [71]:
print(new_matrix)

[[ 1  2  3]
 [43  2  5]
 [ 6  5  2]]


In [73]:
print(new_matrix[0:2],[1,2])

[[ 1  2  3]
 [43  2  5]] [1, 2]


In [75]:
#update matrix

In [77]:
print('og matrix', new_matrix)

og matrix [[ 1  2  3]
 [43  2  5]
 [ 6  5  2]]


In [79]:
new_matrix[0,2]=200
new_matrix

array([[  1,   2, 200],
       [ 43,   2,   5],
       [  6,   5,   2]])

In [81]:
new_matrix[1,0]=110
new_matrix

array([[  1,   2, 200],
       [110,   2,   5],
       [  6,   5,   2]])

In [83]:
#Subsetting-So what is subsetting ? subsetting means when we wann to fetch only few dara from matrix then we use subsetting method.

In [85]:
mat=np.array(ri(10,100,15)).reshape(3,5)
print('Matrix of random 2 digit number \n------\n',mat)

Matrix of random 2 digit number 
------
 [[38 78 75 48 91]
 [87 62 69 45 36]
 [27 14 39 83 24]]


In [87]:
print("Elements greater than 50\n ",mat[mat>50])

Elements greater than 50
  [78 75 91 87 62 69 83]


In [92]:
print(np.where(mat==45))

(array([1]), array([3]))


In [ ]:
#You can also use np.where to return some data based on condtion

In [94]:
num=45
np.where(num>50,'Part Time', 'Full Time')

array('Full Time', dtype='<U9')

In [96]:
#Universal Functions

In [108]:
mat1=np.array(ri(2,11,9)).reshape(3,3)
mat2=np.array(ri(3,12,9)).reshape(3,3)

print("\n 1st Matric \n---------------\n",mat1)
print("\n 2st Matric \n---------------\n",mat2)


 1st Matric 
---------------
 [[ 8  6 10]
 [ 8 10  2]
 [10  4  6]]

 2st Matric 
---------------
 [[ 4  4  6]
 [ 4  4 10]
 [10  3  9]]


In [112]:
print('Division of 2: \n', mat1/mat2)

Division of 2: 
 [[2.         1.5        1.66666667]
 [2.         2.5        0.2       ]
 [1.         1.33333333 0.66666667]]


In [114]:
print('\n Linear combination : 3*A - 2*B \n', 3*mat1 - 2*mat2)


 Linear combination : 3*A - 2*B 
 [[ 16  10  18]
 [ 16  22 -14]
 [ 10   6   0]]


In [116]:
#Broadcasting-
#NumPy operations are usually performed on pairs of arrays on an element-by-element basis. 
#In the simplest case, the two arrays must have exactly the same shape.
#NumPy broadcasting rules relax this constraint when the array shapes meet certain conditions.
#When operating on two arrays, NumPy compares their shapes element-wise, starting with the trailing dimensions 
#and working its way forward. Two dimensions are compatible when they are equal or when one of them is 1.

In [120]:
matzero=np.zeros((3,3))
print(matzero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [122]:
#create a rank1 ndarray with 3 values

In [124]:
rowmat=np.array([[1,2,3]])
print(rowmat)

[[1 2 3]]


In [132]:
#add 2 matrices of diff shape
x= matzero + rowmat # add to each row of 'matzero' using broadcasting

In [134]:
x

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [136]:
#Transpose of matrix
rowmat_t= rowmat.T # T is use for transpose it convert column into row & vice versa

In [138]:
rowmat_t #column matrix

array([[1],
       [2],
       [3]])

In [140]:
y= rowmat_t + matzero

In [142]:
y #add columns of rowmat_t to matzero

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [146]:
colmat=np.array([[3,5,7]]).T
colmat

array([[3],
       [5],
       [7]])

In [148]:
#Array Math

In [150]:
mat1=np.array(ri(1,10,9)).reshape(3,3)
mat2=np.array(ri(1,10,9)).reshape(3,3)

print("\n 1st Matrix of random single digit number\n---------------------------\n",mat1)
print("\n 2nd Matrix of random single digit number\n---------------------------\n",mat2)


 1st Matrix of random single digit number
---------------------------
 [[3 3 4]
 [9 7 8]
 [9 8 6]]

 2nd Matrix of random single digit number
---------------------------
 [[8 7 2]
 [4 1 8]
 [5 5 4]]


In [152]:
print("\n sq-root of 1st Matrix using np\n",'-'*50,"\n",np.sqrt(mat1))
print("\n square of 2nd Matrix using np\n",'-'*50,"\n",np.square(mat2))


 sq-root of 1st Matrix using np
 -------------------------------------------------- 
 [[1.73205081 1.73205081 2.        ]
 [3.         2.64575131 2.82842712]
 [3.         2.82842712 2.44948974]]

 square of 2nd Matrix using np
 -------------------------------------------------- 
 [[64 49  4]
 [16  1 64]
 [25 25 16]]
